---
- hosts: all
  tasks:
  - name: install basic packages
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
    with_items:
      - git
      - nginx

  - git:
     repo: https://github.com/Neilpang/acme.sh.git
     dest: /root/acme.sh
  - name: get pull request
    command: cd /root/acme.sh && git fetch origin pull/2470/head && git checkout -b pullrequest FETCH_HEAD