---
- hosts: all
  tasks:
  - name: install basic packages
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
    with_items:
      - git
      - nginx

  - git:
     repo: https://github.com/Neilpang/acme.sh.git
     dest: /root/acme.sh
  - name: get pull request
    command: 
      cmd: git fetch origin pull/2470/head
      chdir: /root/acme.sh
  - name: get pull request2
    command: 
      cmd: git checkout -b pullrequest FETCH_HEAD
      chdir: /root/acme.sh