---
- hosts: all
  tasks:
  - name: install basic packages
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
    with_items:
      - git
      - nginx

  - git:
     repo: https://github.com/Neilpang/acme.sh
     dest: /root/acme.sh
     refspec: '+refs/pull/2470'