---
- hosts: all
  vars_files:
    - /root/vars.yaml
  tasks:
  - name: install basic packages
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
    with_items:
      - git
      - nginx

  - name: check if git repo present
    stat:
      path: /root/acme.sh/dnsapi/dns_dynv6.sh
    register: acme_present

  - git:
     repo: https://github.com/Neilpang/acme.sh.git
     dest: /root/acme.sh
    when: acme_present.stat.exists == true
  - name: get pull request
    command: 
      cmd: git fetch origin pull/2470/head
      chdir: /root/acme.sh
  - name: get pull request2
    command: 
      cmd: git checkout -b pullrequest FETCH_HEAD
      chdir: /root/acme.sh
  - name: add A record
    command:
      cmd: ssh api@dynv6.com -i /root/.ssh/dynv6 hosts {{ host }} records set {{ record }} a addr {{ ip }}
